### ISSUE TITLE
Notendur - skráning

### ISSUE THREAD

**Issue by ingvarorn** [idega/fiskistofa#10]
Ýmislegt !
Þarf að samræma útlit, ekki sama leturgerð hér og annars staðar
Við notendakenni stendur að "Notendanafnið er alltaf kennitala ..." en það er ekki rétt ?
Samræma nöfn á sviðum, þe. t.d. notendakenni vs notendanafn
Stækka nafnasvið - sést ekki allt nafnið ef það er lengra en X stafir
Á að bjóða upp á Land hérna ?

**Comment by idega** [comment]
Moved to clockingit
