### ISSUE TITLE
Breyta lykilorði - núverandi lykilorð kemur sjálfkrafa í innsláttarsvæði

### ISSUE THREAD

**Issue by ingvarorn** [idega/fiskistofa#11]
Loggaður inn sem HB Grandi, þegar ég fer í að breyta lykilorði þá skráist sjálfkrafa núverandi lykilorð - ætti að vera tómt sviðið

**Comment by ingvarorn** [comment]
Virðist ekki gerast alltaf en þó stundum

**Comment by bluebottle** [comment]
Ættir kannski að slökkva á því að láta browserinn þinn vera að muna lykilorð. Kemur kerfinu sem sagt ekkert við :D
