### ISSUE TITLE
Undirnotandi - er í rugli eftir innskráningu

### ISSUE THREAD

**Issue by ingvarorn** [idega/fiskistofa#14]
Logga inn sem undirnotandi sem hefur aðgang að 2 þjónustum (brotaskýrsla og alm.vleyfi)
Sé ekki skipin sem tengjast minni útgerð.
Þú hefur aðgang að 3 þjónustum "Template", "Fiskistofa", og "Fiskistofa TC" ! Er ekkert á bakvið þetta

**Comment by idega** [comment]
Moved to clockingit
