### ISSUE TITLE
New check for "utgerdarflokkur"

### ISSUE THREAD

**Issue by ingvarorn** [idega/fiskistofa#20]
A vessel that has the status of "-10" for "utgerdarflokkur" will not be granted a fishing license.
Currently the value of utgerdarflokkur is returned in getskipinfo as
                ns0:utgFlHeitiNúllflokkur/ns0:utgFlHeiti
Perhaps we should also return the actual status-code and check for that ?

**Comment by ingvarorn** [comment]
webservice has been updated so that it now returns the status-code.
Application forms need to check if this value is -10, in that case application cannot be submitted.

**Comment by idega** [comment]
Moved to clockingit
