### ISSUE TITLE
Check for transfer of quota (flutningur aflaheimilda) does not give error

### ISSUE THREAD

**Issue by ingvarorn** [idega/fiskistofa#25]
Webservice "getaflamflutningstekkforskip" returns correct value "0" for vessel 2478 which should give error in application form

**Comment by bluebottle** [comment]
Tékkið virkar fínt núna en þarf að snúa við birtingunni. Reyndar er þessi lýsing frá Ingvari akkurat öfug miðað við póstinn sem ég fékk frá honum í dag (þar stendur að 1 eigi að skila villu en ekki 0 :))

**Comment by ingvarorn** [comment]
nei ég held þú sért eitthvað að misskilja þetta, 1 þýðir að allt sé í lagi - engin villa
 

github:  Webservice "getaflamflutningstekkforskip" returns correct value "0" for vessel 2478 which should give error in application form 
sem sagt "0" = Villa - stoppa

## það er sem sagt rétt að hann skilar 0 því ég var búinn að stilla hann þannig til að sjá hvort kæmi villa

póstur í dag:
    ns0:messageSkipið hefur flutt meira til sín á fiskveiðiárinu en frá sér/ns0:message    ns0:isok1/ns0:isoksem sagt "1" = OK , ekki stoppa
 
ég held það sé ekkert conflict hér ?
 
kv, I-----bluebottle reply@reply.github.com wrote: ----- 

To: ingvar@fiskistofa.isFrom: bluebottle reply@reply.github.comDate: 13.04.2011 17:14Subject: Re: [GitHub] Check for transfer of quota (flutningur aflaheimilda) does not give error [idega/fiskistofa GH-25]Tékkið virkar fínt núna en þarf að snúa við birtingunni. Reyndar er þessi lýsing frá Ingvari akkurat öfug miðað við póstinn sem ég fékk frá honum í dag (þar stendur að 1 eigi að skila villu en ekki 0 :))-- Reply to this email directly or view it on GitHub:https://github.com/idega/fiskistofa/issues/25#comment_996612

**Comment by ingvarorn** [comment]
bara að þetta virki rétt á morgun !
 
spurning um að biðja til Guðs eða Allah, gá hvort það hjálpi til ? Betra seint en aldrei :!-----Páll Helgason palli@idega.com wrote: ----- 

To: Ingvar Örn Guðjónsson ingvar@fiskistofa.isFrom: Páll Helgason palli@idega.comDate: 13.04.2011 20:54Cc: reply@reply.github.comSubject: Re: [GitHub] Check for transfer of quota (flutningur aflaheimilda) does not give error [idega/fiskistofa GH-25]Ok. Er alla vega öfugt í forminu núna. Ég sendi inn true og þá stoppar þetta. 

/p

¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
Pall Helgason
Senior Software Engineer

palli@idega.com

¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
IOS hf.  ı  Hlíðarsmári 2  ı  201 Kópavogur  ı  Iceland
Tel. +354 554 7557

www.idega.org ı  idega@idega.com

Murphy's Laws: (1) If anything can go wrong, it will. (2) Nothing is as easy as it looks. (3) Everything takes longer than you think it will.
On 13.4.2011, at 18:52, Ingvar Örn Guðjónsson wrote:
nei ég held þú sért eitthvað að misskilja þetta, 1 þýðir að allt sé í lagi - engin villa
 

github:  Webservice "getaflamflutningstekkforskip" returns correct value "0" for vessel 2478 which should give error in application form 
sem sagt "0" = Villa - stoppa

## það er sem sagt rétt að hann skilar 0 því ég var búinn að stilla hann þannig til að sjá hvort kæmi villa

póstur í dag:
    ns0:messageSkipið hefur flutt meira til sín á fiskveiðiárinu en frá sér/ns0:message    ns0:isok1/ns0:isoksem sagt "1" = OK , ekki stoppa
 
ég held það sé ekkert conflict hér ?
 
kv, I-----bluebottle reply@reply.github.com wrote: ----- 

To: ingvar@fiskistofa.isFrom: bluebottle reply@reply.github.comDate: 13.04.2011 17:14Subject: Re: [GitHub] Check for transfer of quota (flutningur aflaheimilda) does not give error [idega/fiskistofa GH-25]Tékkið virkar fínt núna en þarf að snúa við birtingunni. Reyndar er þessi lýsing frá Ingvari akkurat öfug miðað við póstinn sem ég fékk frá honum í dag (þar stendur að 1 eigi að skila villu en ekki 0 :))-- Reply to this email directly or view it on GitHub:https://github.com/idega/fiskistofa/issues/25#comment_996612
