### ISSUE TITLE
Úthlutun veiðisvæðis í dragnót er ekki að virka

### ISSUE THREAD

**Issue by ingvarorn** [idega/fiskistofa#28]
Skilar alltaf til baka "Dragnótaveiðisvæði finnst".
Á að skila til baka númeri eða nafni svæðis ef póstnr og heimahöfn tilheyra sama veiðisvæði.
Annars á að skila villu ef póstnr og heimahöfn tilheyra ekki sama veiðisvæði.

**Comment by idega** [comment]
Moved to clockingit
