### ISSUE TITLE
Grásleppa - lagfæra vefþjónustu

### ISSUE THREAD

**Issue by ingvarorn** [idega/fiskistofa#33]
Skoða tékkin á grásleppuleyfum sem mér sýnist ekki vera rétt í VEIDILEYFI_WS

Það þarf að tékka í töfluna kvoti.grasleppurettindi, ekki kvoti.grasleppa, og horfa þá til að STADA_LEYFIS sé = "V"   (virkt)

Þannig að function getGrasleppuSkipNrUtgerdar(...) tekur með sér kt. útgerðar og þarf að skila til baka þeim skipum útgerðar sem finnast í kvoti.grasleppurettindi með STADA_LEYFIS = "V"

Einnig þarf function getHefurUtgerdGrasleppuvlByKt(...) að leita í kvoti.grasleppurettindi með STADA_LEYFIS = "V"

**Comment by ingvarorn** [comment]
SVENNI: "Ég er búinn að skipta um töflu sem kallað er í. Ég held samt að ég eigi ekki að filtera á að STADA_LEYFIS sé 'V'. Skv. símtali við Baldvin þá hefði ég haldið að það mætti sækja um leyfi á á grásleppuréttindi sem eru í geymslu, en þau breyta þá um stöðu og verða virk, Ingvar þú tékkar það kannski betur."

INGVAR: "Ég var að tala við Jón Valgeir, hann vill að þú sýnir bara "V" virk leyfi í skipalistanum.

Ef umsækjandi er með leyfi í geymslu, þá verður hann fyrst að hafa samband við Fiskistofu og láta virkja leyfið áður en hann getur sent inn umsókn."

**Comment by sveinnh** [comment]
Nú er filterað á stada_leyfis='V'

**Comment by ingvarorn** [comment]
Gott, loka málinu
